### ISSUE TITLE
Issues about loading params for pretrained CLAP

### ISSUE THREAD

**Issue by apple-yinhan** [Audio-AGI/dcase2024_task9_baseline#1]
When I run the baseline, a bug is:
 raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
 RuntimeError: Error(s) in loading state_dict for CLAP:
        Unexpected key(s) in state_dict: "text_branch.embeddings.position_ids". 
        
This happens in: model.load_state_dict(ckpt)

But I do download the music_speech_audioset_epoch_15_esc_89.98.pt and put it in the right folder.
So I have set model.load_state_dict(ckpt, stirct = False)

Will this affect the results of the baseline?

**Comment by liuxubo717** [comment]
Can you reproduce the results on the Validation (synth)?

------------------------------------------------------
Evaluation on DCASE T9 synthetic validation set.
Results: SDR: SDR: 5.708, SDRi: 5.673, SISDR: 3.862

**Comment by apple-yinhan** [comment]
Yes, I can. It seems that this does not affect anything. Thanks.
